#!/usr/bin/env python
# -*- coding: utf-8 -*-
### BEGIN INIT INFO
# Provides:          il2dsd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IL-2 FB DS daemon
# Description:       Run IL-2 FB Dedicated Server as daemon.
### END INIT INFO
"""
IL-2 FB Dedicated Server daemon. Run this file as an executable and pass one
of 'start', 'stop', 'status' or 'restart' commands to control IL-2 DS daemon or
to get its status respectively.

Look through project's REAME for details and instructions. Home page:
https://github.com/IL2HorusTeam/il2dsd
"""
import ConfigParser
import os
import sys

from wine_deamonizer import WineDaemon


CONFIG_PATH = '/etc/il2dsd.conf'
SECTION_NAME = 'Locations'
OPTION_NAME = 'exe_path'


class IL2DSDaemon(WineDaemon):
    """
    IL-2 FB Dedicated Server daemon.
    """
    def post_start(self):
        """
        Wait for server to print command prompt indicating it's loaded.
        """
        while True:
            line = self.process.stdout.readline()
            if line == '':
                break
            if line.startswith("1>"):
                break


def get_exe_path():
    if not os.path.exists(CONFIG_PATH):
        sys.stderr.write("Config file '{path}' not found!\n".format(
                         path=CONFIG_PATH))
        sys.exit(1)

    config = ConfigParser.ConfigParser()

    try:
        if not config.read(CONFIG_PATH):
            sys.stderr.write(
                "Failed to read config file {path}. Make sure it is "
                "present and contains valid data.\n".format(path=CONFIG_PATH))
            sys.exit(1)
    except Exception as e:
        sys.stderr.write("Failed to read config file {path}: {err}.\n".format(
            path=CONFIG_PATH, err=unicode(e)))
        sys.exit(1)

    try:
        exe_path = config.get(SECTION_NAME, OPTION_NAME).strip()
    except ConfigParser.NoSectionError:
        sys.stderr.write(
            "Missing section '{section}' in config file '{path}'.\n" .format(
                section=SECTION_NAME, path=CONFIG_PATH))
        sys.exit(1)
    except ConfigParser.NoOptionError:
        sys.stderr.write(
            "Missing option '{option}' in section '{section}' in config file "
            "'{path}'.\n".format(option=OPTION_NAME, section=SECTION_NAME,
                                 path=CONFIG_PATH))
        sys.exit(1)
    except Exception as e:
        sys.stderr.write(
            "Failed to get '{section}':'{option}' from '{path}' config file: "
            "{err}.\n" .format(option=OPTION_NAME, section=SECTION_NAME,
                               path=CONFIG_PATH, err=unicode(e)))
        sys.exit(1)

    if os.path.exists(exe_path):
        return exe_path
    else:
        sys.stderr.write(
            "Executable file '{path}' does not exist.\n".format(path=exe_path))
        sys.exit(1)


def main():
    exe_path = get_exe_path()
    daemon = IL2DSDaemon(exe_path=exe_path, timeout=120.0)

    def on_wrong_usage():
        print "usage: {name} {commands}".format(
            name=sys.argv[0], commands='|'.join(daemon.commands))
        sys.exit(1)

    if len(sys.argv) != 2:
        on_wrong_usage()

    # Provide support for Debian's 'force-reload':
    cmd_name = sys.argv[1]
    if cmd_name == 'force-reload':
        cmd_name = 'restart'

    if not daemon(cmd_name):
        on_wrong_usage()


if __name__ == "__main__":
    main()
